### ISSUE TITLE
Seeds duplication bug

### ISSUE THREAD

**Issue by LTHCTheMaster** [Stoupy51/StardustFragment#1]
In the last public release of Stardust Fragment, if we spam the placement of a seed from stardust (for example, the legendary seed) on the wrong block (a block which isn't a lime concrete for the legendary seed), we can duplicate the seed.

**Comment by Stoupy51** [comment]
[[Bug fix commit]](https://github.com/Stoupy51/StardustFragment/commit/79cd4784fa289dffb98d0d7b6693fdcd47afca42)

Seeds could be duplicated when stacking up them on placement because of multiple destroy check running.

Fixed for **Stardust Fragment [v3.2.0]**
