### ISSUE TITLE
Resource pack conflict with Mechanization

### ISSUE THREAD

**Issue by Gryhyphen** [Stoupy51/StardustFragment#2]
Version:
Stardust.Fragment.Resource.Pack.v3.4.x.zip
MechanizationResourcepack_v4.0.4.zip
Minecraft.v1.19.2

Problem:
Seems to be an issue with item frames.

The Pneumatic Exit-Point and Pneumatic Entry-Point from Mechanization use item frames.
The seeds like diamond seeds, stardust seeds, etc. from Stardust.Fragment also seem to use item frames.

Depending on the ordering of the resource packs, either the Mechanization item frames are replaced with stardust seed textures, or, mechanization item frames are fine, and stardust.fragment seeds are just regular-old item frame textures.

![image](https://user-images.githubusercontent.com/7694072/186147294-e573f8e4-1758-4d33-bbf9-2885f0d98d3a.png)
![image](https://user-images.githubusercontent.com/7694072/186147417-bb69c46d-d599-40ba-aed2-219bafc89f6a.png)

Awesome datapack btw! It's so freaking cool!

**Comment by LTHCTheMaster** [comment]
Hello, use [https://mito.thenuclearnexus.live](https://mito.thenuclearnexus.live) to merge resource packs and avoid the aforementioned problem.

**Comment by Gryhyphen** [comment]
Ty for prompt response!
