### ISSUE TITLE
Tech Reborn, Industrial Revolution, Powah, Applied Energistics 2 compatibility?

### ISSUE THREAD

**Issue by vadim-a-yegorov** [Stoupy51/StardustFragment#3]
Is it implemented, planned or does not align with project philosophy?

**Comment by Stoupy51** [comment]
Hello,

Firstly, datapacks are vanilla features, they're not the same as mods, they do not contain any Java code so they can't communicate with mods by any way (unless someone make a mod for it, which isn't the case).

Secondly, as a datapacker, I only provide compatibility experience with other datapacks. Even if I wanted, the overhead of making special compatibility with mods is unreachable and pretty useless as 99% of people playing with datapacks don't use any mods, as well as the other way round (people using mods don't use datapacks)

**Comment by vadim-a-yegorov** [comment]
To make it compatible a compat mod required, yes you're right. I understand, it's not designed for tech mods ecosystem, it's more for datapack based projects.
